title: Aurumtech LTD
author: Akron254
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a description of my new testng site in github.
  This page is only meant for educational and tutorial purposes only.
  Please use this site as the description states.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-time-machine
